################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
core/k_buf_queue.o: /Users/snowyang/workspace/AliOS-Things/kernel/rhino/core/k_buf_queue.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: GNU Compiler'
	"/Applications/ti/ccsv6/tools/compiler/gcc-arm-none-eabi-4_9-2015q3/bin/arm-none-eabi-gcc" -c -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSYSINFO_OS_VERSION=\"APP-1.0.0\" -DSYSINFO_PRODUCT_MODEL=\"ALI_AOS_STM32L433RCTxP\" -DSYSINFO_DEVICE_NAME=\"STM32L433RCTxP\" -DSYSINFO_KERNEL_VERSION=\"AOS-R-1.3.0\" -DSYSINFO_APP_VERSION=\"APP-1.0.0\" -DSTDIO_UART=0 -DCONFIG_NO_TCPIP -DRHINO_CONFIG_TICK_TASK=0 -DCONFIG_AOS_KV_MULTIPTN_MODE -DCONFIG_AOS_KV_PTN=6 -DCONFIG_AOS_KV_SECOND_PTN=7 -DCONFIG_AOS_KV_PTN_SIZE=4096 -DCONFIG_AOS_KV_BUFFER_SIZE=8192 -D__BSD_VISIBLE -DRHINO_CONFIG_TICK_TASK=0 -D__MSP432P401R__ -DTARGET_IS_MSP432P4XX -DMX_DEBUG -I"/Applications/ti/ccsv6/tools/compiler/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_button" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_color_led" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_sht20" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_VGM128064" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/hal" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/AliCloud_SDS" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/emhost" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/jsmn" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/inc" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/inc/CMSIS" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/driverlib/MSP432P4xx" -I"/Users/snowyang/workspace/AliOS-Things/include" -I"/Users/snowyang/workspace/AliOS-Things/kernel/rhino/core/include" -I"/Users/snowyang/workspace/AliOS-Things/platform/arch/arm/armv7m/gcc/m4" -I"/Users/snowyang/workspace/AliOS-Things/include/hal" -I"/Users/snowyang/workspace/AliOS-Things/kernel/vcall/aos" -I"/Users/snowyang/workspace/AliOS-Things/board/msp432_launchpad" -ffunction-sections -fdata-sections -fsingle-precision-constant -g -gdwarf-3 -gstrict-dwarf -Wall -std=c99 -fshort-wchar -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o"$@" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

core/k_dyn_mem_proc.o: /Users/snowyang/workspace/AliOS-Things/kernel/rhino/core/k_dyn_mem_proc.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: GNU Compiler'
	"/Applications/ti/ccsv6/tools/compiler/gcc-arm-none-eabi-4_9-2015q3/bin/arm-none-eabi-gcc" -c -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSYSINFO_OS_VERSION=\"APP-1.0.0\" -DSYSINFO_PRODUCT_MODEL=\"ALI_AOS_STM32L433RCTxP\" -DSYSINFO_DEVICE_NAME=\"STM32L433RCTxP\" -DSYSINFO_KERNEL_VERSION=\"AOS-R-1.3.0\" -DSYSINFO_APP_VERSION=\"APP-1.0.0\" -DSTDIO_UART=0 -DCONFIG_NO_TCPIP -DRHINO_CONFIG_TICK_TASK=0 -DCONFIG_AOS_KV_MULTIPTN_MODE -DCONFIG_AOS_KV_PTN=6 -DCONFIG_AOS_KV_SECOND_PTN=7 -DCONFIG_AOS_KV_PTN_SIZE=4096 -DCONFIG_AOS_KV_BUFFER_SIZE=8192 -D__BSD_VISIBLE -DRHINO_CONFIG_TICK_TASK=0 -D__MSP432P401R__ -DTARGET_IS_MSP432P4XX -DMX_DEBUG -I"/Applications/ti/ccsv6/tools/compiler/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_button" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_color_led" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_sht20" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_VGM128064" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/hal" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/AliCloud_SDS" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/emhost" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/jsmn" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/inc" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/inc/CMSIS" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/driverlib/MSP432P4xx" -I"/Users/snowyang/workspace/AliOS-Things/include" -I"/Users/snowyang/workspace/AliOS-Things/kernel/rhino/core/include" -I"/Users/snowyang/workspace/AliOS-Things/platform/arch/arm/armv7m/gcc/m4" -I"/Users/snowyang/workspace/AliOS-Things/include/hal" -I"/Users/snowyang/workspace/AliOS-Things/kernel/vcall/aos" -I"/Users/snowyang/workspace/AliOS-Things/board/msp432_launchpad" -ffunction-sections -fdata-sections -fsingle-precision-constant -g -gdwarf-3 -gstrict-dwarf -Wall -std=c99 -fshort-wchar -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o"$@" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

core/k_err.o: /Users/snowyang/workspace/AliOS-Things/kernel/rhino/core/k_err.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: GNU Compiler'
	"/Applications/ti/ccsv6/tools/compiler/gcc-arm-none-eabi-4_9-2015q3/bin/arm-none-eabi-gcc" -c -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSYSINFO_OS_VERSION=\"APP-1.0.0\" -DSYSINFO_PRODUCT_MODEL=\"ALI_AOS_STM32L433RCTxP\" -DSYSINFO_DEVICE_NAME=\"STM32L433RCTxP\" -DSYSINFO_KERNEL_VERSION=\"AOS-R-1.3.0\" -DSYSINFO_APP_VERSION=\"APP-1.0.0\" -DSTDIO_UART=0 -DCONFIG_NO_TCPIP -DRHINO_CONFIG_TICK_TASK=0 -DCONFIG_AOS_KV_MULTIPTN_MODE -DCONFIG_AOS_KV_PTN=6 -DCONFIG_AOS_KV_SECOND_PTN=7 -DCONFIG_AOS_KV_PTN_SIZE=4096 -DCONFIG_AOS_KV_BUFFER_SIZE=8192 -D__BSD_VISIBLE -DRHINO_CONFIG_TICK_TASK=0 -D__MSP432P401R__ -DTARGET_IS_MSP432P4XX -DMX_DEBUG -I"/Applications/ti/ccsv6/tools/compiler/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_button" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_color_led" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_sht20" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_VGM128064" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/hal" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/AliCloud_SDS" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/emhost" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/jsmn" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/inc" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/inc/CMSIS" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/driverlib/MSP432P4xx" -I"/Users/snowyang/workspace/AliOS-Things/include" -I"/Users/snowyang/workspace/AliOS-Things/kernel/rhino/core/include" -I"/Users/snowyang/workspace/AliOS-Things/platform/arch/arm/armv7m/gcc/m4" -I"/Users/snowyang/workspace/AliOS-Things/include/hal" -I"/Users/snowyang/workspace/AliOS-Things/kernel/vcall/aos" -I"/Users/snowyang/workspace/AliOS-Things/board/msp432_launchpad" -ffunction-sections -fdata-sections -fsingle-precision-constant -g -gdwarf-3 -gstrict-dwarf -Wall -std=c99 -fshort-wchar -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o"$@" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

core/k_event.o: /Users/snowyang/workspace/AliOS-Things/kernel/rhino/core/k_event.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: GNU Compiler'
	"/Applications/ti/ccsv6/tools/compiler/gcc-arm-none-eabi-4_9-2015q3/bin/arm-none-eabi-gcc" -c -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSYSINFO_OS_VERSION=\"APP-1.0.0\" -DSYSINFO_PRODUCT_MODEL=\"ALI_AOS_STM32L433RCTxP\" -DSYSINFO_DEVICE_NAME=\"STM32L433RCTxP\" -DSYSINFO_KERNEL_VERSION=\"AOS-R-1.3.0\" -DSYSINFO_APP_VERSION=\"APP-1.0.0\" -DSTDIO_UART=0 -DCONFIG_NO_TCPIP -DRHINO_CONFIG_TICK_TASK=0 -DCONFIG_AOS_KV_MULTIPTN_MODE -DCONFIG_AOS_KV_PTN=6 -DCONFIG_AOS_KV_SECOND_PTN=7 -DCONFIG_AOS_KV_PTN_SIZE=4096 -DCONFIG_AOS_KV_BUFFER_SIZE=8192 -D__BSD_VISIBLE -DRHINO_CONFIG_TICK_TASK=0 -D__MSP432P401R__ -DTARGET_IS_MSP432P4XX -DMX_DEBUG -I"/Applications/ti/ccsv6/tools/compiler/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_button" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_color_led" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_sht20" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_VGM128064" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/hal" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/AliCloud_SDS" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/emhost" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/jsmn" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/inc" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/inc/CMSIS" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/driverlib/MSP432P4xx" -I"/Users/snowyang/workspace/AliOS-Things/include" -I"/Users/snowyang/workspace/AliOS-Things/kernel/rhino/core/include" -I"/Users/snowyang/workspace/AliOS-Things/platform/arch/arm/armv7m/gcc/m4" -I"/Users/snowyang/workspace/AliOS-Things/include/hal" -I"/Users/snowyang/workspace/AliOS-Things/kernel/vcall/aos" -I"/Users/snowyang/workspace/AliOS-Things/board/msp432_launchpad" -ffunction-sections -fdata-sections -fsingle-precision-constant -g -gdwarf-3 -gstrict-dwarf -Wall -std=c99 -fshort-wchar -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o"$@" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

core/k_idle.o: /Users/snowyang/workspace/AliOS-Things/kernel/rhino/core/k_idle.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: GNU Compiler'
	"/Applications/ti/ccsv6/tools/compiler/gcc-arm-none-eabi-4_9-2015q3/bin/arm-none-eabi-gcc" -c -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSYSINFO_OS_VERSION=\"APP-1.0.0\" -DSYSINFO_PRODUCT_MODEL=\"ALI_AOS_STM32L433RCTxP\" -DSYSINFO_DEVICE_NAME=\"STM32L433RCTxP\" -DSYSINFO_KERNEL_VERSION=\"AOS-R-1.3.0\" -DSYSINFO_APP_VERSION=\"APP-1.0.0\" -DSTDIO_UART=0 -DCONFIG_NO_TCPIP -DRHINO_CONFIG_TICK_TASK=0 -DCONFIG_AOS_KV_MULTIPTN_MODE -DCONFIG_AOS_KV_PTN=6 -DCONFIG_AOS_KV_SECOND_PTN=7 -DCONFIG_AOS_KV_PTN_SIZE=4096 -DCONFIG_AOS_KV_BUFFER_SIZE=8192 -D__BSD_VISIBLE -DRHINO_CONFIG_TICK_TASK=0 -D__MSP432P401R__ -DTARGET_IS_MSP432P4XX -DMX_DEBUG -I"/Applications/ti/ccsv6/tools/compiler/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_button" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_color_led" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_sht20" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_VGM128064" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/hal" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/AliCloud_SDS" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/emhost" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/jsmn" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/inc" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/inc/CMSIS" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/driverlib/MSP432P4xx" -I"/Users/snowyang/workspace/AliOS-Things/include" -I"/Users/snowyang/workspace/AliOS-Things/kernel/rhino/core/include" -I"/Users/snowyang/workspace/AliOS-Things/platform/arch/arm/armv7m/gcc/m4" -I"/Users/snowyang/workspace/AliOS-Things/include/hal" -I"/Users/snowyang/workspace/AliOS-Things/kernel/vcall/aos" -I"/Users/snowyang/workspace/AliOS-Things/board/msp432_launchpad" -ffunction-sections -fdata-sections -fsingle-precision-constant -g -gdwarf-3 -gstrict-dwarf -Wall -std=c99 -fshort-wchar -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o"$@" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

core/k_mm.o: /Users/snowyang/workspace/AliOS-Things/kernel/rhino/core/k_mm.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: GNU Compiler'
	"/Applications/ti/ccsv6/tools/compiler/gcc-arm-none-eabi-4_9-2015q3/bin/arm-none-eabi-gcc" -c -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSYSINFO_OS_VERSION=\"APP-1.0.0\" -DSYSINFO_PRODUCT_MODEL=\"ALI_AOS_STM32L433RCTxP\" -DSYSINFO_DEVICE_NAME=\"STM32L433RCTxP\" -DSYSINFO_KERNEL_VERSION=\"AOS-R-1.3.0\" -DSYSINFO_APP_VERSION=\"APP-1.0.0\" -DSTDIO_UART=0 -DCONFIG_NO_TCPIP -DRHINO_CONFIG_TICK_TASK=0 -DCONFIG_AOS_KV_MULTIPTN_MODE -DCONFIG_AOS_KV_PTN=6 -DCONFIG_AOS_KV_SECOND_PTN=7 -DCONFIG_AOS_KV_PTN_SIZE=4096 -DCONFIG_AOS_KV_BUFFER_SIZE=8192 -D__BSD_VISIBLE -DRHINO_CONFIG_TICK_TASK=0 -D__MSP432P401R__ -DTARGET_IS_MSP432P4XX -DMX_DEBUG -I"/Applications/ti/ccsv6/tools/compiler/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_button" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_color_led" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_sht20" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_VGM128064" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/hal" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/AliCloud_SDS" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/emhost" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/jsmn" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/inc" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/inc/CMSIS" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/driverlib/MSP432P4xx" -I"/Users/snowyang/workspace/AliOS-Things/include" -I"/Users/snowyang/workspace/AliOS-Things/kernel/rhino/core/include" -I"/Users/snowyang/workspace/AliOS-Things/platform/arch/arm/armv7m/gcc/m4" -I"/Users/snowyang/workspace/AliOS-Things/include/hal" -I"/Users/snowyang/workspace/AliOS-Things/kernel/vcall/aos" -I"/Users/snowyang/workspace/AliOS-Things/board/msp432_launchpad" -ffunction-sections -fdata-sections -fsingle-precision-constant -g -gdwarf-3 -gstrict-dwarf -Wall -std=c99 -fshort-wchar -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o"$@" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

core/k_mm_blk.o: /Users/snowyang/workspace/AliOS-Things/kernel/rhino/core/k_mm_blk.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: GNU Compiler'
	"/Applications/ti/ccsv6/tools/compiler/gcc-arm-none-eabi-4_9-2015q3/bin/arm-none-eabi-gcc" -c -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSYSINFO_OS_VERSION=\"APP-1.0.0\" -DSYSINFO_PRODUCT_MODEL=\"ALI_AOS_STM32L433RCTxP\" -DSYSINFO_DEVICE_NAME=\"STM32L433RCTxP\" -DSYSINFO_KERNEL_VERSION=\"AOS-R-1.3.0\" -DSYSINFO_APP_VERSION=\"APP-1.0.0\" -DSTDIO_UART=0 -DCONFIG_NO_TCPIP -DRHINO_CONFIG_TICK_TASK=0 -DCONFIG_AOS_KV_MULTIPTN_MODE -DCONFIG_AOS_KV_PTN=6 -DCONFIG_AOS_KV_SECOND_PTN=7 -DCONFIG_AOS_KV_PTN_SIZE=4096 -DCONFIG_AOS_KV_BUFFER_SIZE=8192 -D__BSD_VISIBLE -DRHINO_CONFIG_TICK_TASK=0 -D__MSP432P401R__ -DTARGET_IS_MSP432P4XX -DMX_DEBUG -I"/Applications/ti/ccsv6/tools/compiler/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_button" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_color_led" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_sht20" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_VGM128064" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/hal" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/AliCloud_SDS" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/emhost" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/jsmn" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/inc" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/inc/CMSIS" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/driverlib/MSP432P4xx" -I"/Users/snowyang/workspace/AliOS-Things/include" -I"/Users/snowyang/workspace/AliOS-Things/kernel/rhino/core/include" -I"/Users/snowyang/workspace/AliOS-Things/platform/arch/arm/armv7m/gcc/m4" -I"/Users/snowyang/workspace/AliOS-Things/include/hal" -I"/Users/snowyang/workspace/AliOS-Things/kernel/vcall/aos" -I"/Users/snowyang/workspace/AliOS-Things/board/msp432_launchpad" -ffunction-sections -fdata-sections -fsingle-precision-constant -g -gdwarf-3 -gstrict-dwarf -Wall -std=c99 -fshort-wchar -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o"$@" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

core/k_mm_debug.o: /Users/snowyang/workspace/AliOS-Things/kernel/rhino/core/k_mm_debug.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: GNU Compiler'
	"/Applications/ti/ccsv6/tools/compiler/gcc-arm-none-eabi-4_9-2015q3/bin/arm-none-eabi-gcc" -c -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSYSINFO_OS_VERSION=\"APP-1.0.0\" -DSYSINFO_PRODUCT_MODEL=\"ALI_AOS_STM32L433RCTxP\" -DSYSINFO_DEVICE_NAME=\"STM32L433RCTxP\" -DSYSINFO_KERNEL_VERSION=\"AOS-R-1.3.0\" -DSYSINFO_APP_VERSION=\"APP-1.0.0\" -DSTDIO_UART=0 -DCONFIG_NO_TCPIP -DRHINO_CONFIG_TICK_TASK=0 -DCONFIG_AOS_KV_MULTIPTN_MODE -DCONFIG_AOS_KV_PTN=6 -DCONFIG_AOS_KV_SECOND_PTN=7 -DCONFIG_AOS_KV_PTN_SIZE=4096 -DCONFIG_AOS_KV_BUFFER_SIZE=8192 -D__BSD_VISIBLE -DRHINO_CONFIG_TICK_TASK=0 -D__MSP432P401R__ -DTARGET_IS_MSP432P4XX -DMX_DEBUG -I"/Applications/ti/ccsv6/tools/compiler/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_button" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_color_led" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_sht20" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_VGM128064" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/hal" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/AliCloud_SDS" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/emhost" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/jsmn" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/inc" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/inc/CMSIS" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/driverlib/MSP432P4xx" -I"/Users/snowyang/workspace/AliOS-Things/include" -I"/Users/snowyang/workspace/AliOS-Things/kernel/rhino/core/include" -I"/Users/snowyang/workspace/AliOS-Things/platform/arch/arm/armv7m/gcc/m4" -I"/Users/snowyang/workspace/AliOS-Things/include/hal" -I"/Users/snowyang/workspace/AliOS-Things/kernel/vcall/aos" -I"/Users/snowyang/workspace/AliOS-Things/board/msp432_launchpad" -ffunction-sections -fdata-sections -fsingle-precision-constant -g -gdwarf-3 -gstrict-dwarf -Wall -std=c99 -fshort-wchar -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o"$@" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

core/k_mutex.o: /Users/snowyang/workspace/AliOS-Things/kernel/rhino/core/k_mutex.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: GNU Compiler'
	"/Applications/ti/ccsv6/tools/compiler/gcc-arm-none-eabi-4_9-2015q3/bin/arm-none-eabi-gcc" -c -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSYSINFO_OS_VERSION=\"APP-1.0.0\" -DSYSINFO_PRODUCT_MODEL=\"ALI_AOS_STM32L433RCTxP\" -DSYSINFO_DEVICE_NAME=\"STM32L433RCTxP\" -DSYSINFO_KERNEL_VERSION=\"AOS-R-1.3.0\" -DSYSINFO_APP_VERSION=\"APP-1.0.0\" -DSTDIO_UART=0 -DCONFIG_NO_TCPIP -DRHINO_CONFIG_TICK_TASK=0 -DCONFIG_AOS_KV_MULTIPTN_MODE -DCONFIG_AOS_KV_PTN=6 -DCONFIG_AOS_KV_SECOND_PTN=7 -DCONFIG_AOS_KV_PTN_SIZE=4096 -DCONFIG_AOS_KV_BUFFER_SIZE=8192 -D__BSD_VISIBLE -DRHINO_CONFIG_TICK_TASK=0 -D__MSP432P401R__ -DTARGET_IS_MSP432P4XX -DMX_DEBUG -I"/Applications/ti/ccsv6/tools/compiler/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_button" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_color_led" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_sht20" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_VGM128064" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/hal" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/AliCloud_SDS" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/emhost" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/jsmn" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/inc" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/inc/CMSIS" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/driverlib/MSP432P4xx" -I"/Users/snowyang/workspace/AliOS-Things/include" -I"/Users/snowyang/workspace/AliOS-Things/kernel/rhino/core/include" -I"/Users/snowyang/workspace/AliOS-Things/platform/arch/arm/armv7m/gcc/m4" -I"/Users/snowyang/workspace/AliOS-Things/include/hal" -I"/Users/snowyang/workspace/AliOS-Things/kernel/vcall/aos" -I"/Users/snowyang/workspace/AliOS-Things/board/msp432_launchpad" -ffunction-sections -fdata-sections -fsingle-precision-constant -g -gdwarf-3 -gstrict-dwarf -Wall -std=c99 -fshort-wchar -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o"$@" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

core/k_obj.o: /Users/snowyang/workspace/AliOS-Things/kernel/rhino/core/k_obj.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: GNU Compiler'
	"/Applications/ti/ccsv6/tools/compiler/gcc-arm-none-eabi-4_9-2015q3/bin/arm-none-eabi-gcc" -c -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSYSINFO_OS_VERSION=\"APP-1.0.0\" -DSYSINFO_PRODUCT_MODEL=\"ALI_AOS_STM32L433RCTxP\" -DSYSINFO_DEVICE_NAME=\"STM32L433RCTxP\" -DSYSINFO_KERNEL_VERSION=\"AOS-R-1.3.0\" -DSYSINFO_APP_VERSION=\"APP-1.0.0\" -DSTDIO_UART=0 -DCONFIG_NO_TCPIP -DRHINO_CONFIG_TICK_TASK=0 -DCONFIG_AOS_KV_MULTIPTN_MODE -DCONFIG_AOS_KV_PTN=6 -DCONFIG_AOS_KV_SECOND_PTN=7 -DCONFIG_AOS_KV_PTN_SIZE=4096 -DCONFIG_AOS_KV_BUFFER_SIZE=8192 -D__BSD_VISIBLE -DRHINO_CONFIG_TICK_TASK=0 -D__MSP432P401R__ -DTARGET_IS_MSP432P4XX -DMX_DEBUG -I"/Applications/ti/ccsv6/tools/compiler/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_button" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_color_led" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_sht20" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_VGM128064" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/hal" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/AliCloud_SDS" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/emhost" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/jsmn" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/inc" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/inc/CMSIS" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/driverlib/MSP432P4xx" -I"/Users/snowyang/workspace/AliOS-Things/include" -I"/Users/snowyang/workspace/AliOS-Things/kernel/rhino/core/include" -I"/Users/snowyang/workspace/AliOS-Things/platform/arch/arm/armv7m/gcc/m4" -I"/Users/snowyang/workspace/AliOS-Things/include/hal" -I"/Users/snowyang/workspace/AliOS-Things/kernel/vcall/aos" -I"/Users/snowyang/workspace/AliOS-Things/board/msp432_launchpad" -ffunction-sections -fdata-sections -fsingle-precision-constant -g -gdwarf-3 -gstrict-dwarf -Wall -std=c99 -fshort-wchar -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o"$@" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

core/k_pend.o: /Users/snowyang/workspace/AliOS-Things/kernel/rhino/core/k_pend.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: GNU Compiler'
	"/Applications/ti/ccsv6/tools/compiler/gcc-arm-none-eabi-4_9-2015q3/bin/arm-none-eabi-gcc" -c -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSYSINFO_OS_VERSION=\"APP-1.0.0\" -DSYSINFO_PRODUCT_MODEL=\"ALI_AOS_STM32L433RCTxP\" -DSYSINFO_DEVICE_NAME=\"STM32L433RCTxP\" -DSYSINFO_KERNEL_VERSION=\"AOS-R-1.3.0\" -DSYSINFO_APP_VERSION=\"APP-1.0.0\" -DSTDIO_UART=0 -DCONFIG_NO_TCPIP -DRHINO_CONFIG_TICK_TASK=0 -DCONFIG_AOS_KV_MULTIPTN_MODE -DCONFIG_AOS_KV_PTN=6 -DCONFIG_AOS_KV_SECOND_PTN=7 -DCONFIG_AOS_KV_PTN_SIZE=4096 -DCONFIG_AOS_KV_BUFFER_SIZE=8192 -D__BSD_VISIBLE -DRHINO_CONFIG_TICK_TASK=0 -D__MSP432P401R__ -DTARGET_IS_MSP432P4XX -DMX_DEBUG -I"/Applications/ti/ccsv6/tools/compiler/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_button" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_color_led" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_sht20" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_VGM128064" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/hal" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/AliCloud_SDS" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/emhost" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/jsmn" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/inc" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/inc/CMSIS" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/driverlib/MSP432P4xx" -I"/Users/snowyang/workspace/AliOS-Things/include" -I"/Users/snowyang/workspace/AliOS-Things/kernel/rhino/core/include" -I"/Users/snowyang/workspace/AliOS-Things/platform/arch/arm/armv7m/gcc/m4" -I"/Users/snowyang/workspace/AliOS-Things/include/hal" -I"/Users/snowyang/workspace/AliOS-Things/kernel/vcall/aos" -I"/Users/snowyang/workspace/AliOS-Things/board/msp432_launchpad" -ffunction-sections -fdata-sections -fsingle-precision-constant -g -gdwarf-3 -gstrict-dwarf -Wall -std=c99 -fshort-wchar -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o"$@" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

core/k_queue.o: /Users/snowyang/workspace/AliOS-Things/kernel/rhino/core/k_queue.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: GNU Compiler'
	"/Applications/ti/ccsv6/tools/compiler/gcc-arm-none-eabi-4_9-2015q3/bin/arm-none-eabi-gcc" -c -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSYSINFO_OS_VERSION=\"APP-1.0.0\" -DSYSINFO_PRODUCT_MODEL=\"ALI_AOS_STM32L433RCTxP\" -DSYSINFO_DEVICE_NAME=\"STM32L433RCTxP\" -DSYSINFO_KERNEL_VERSION=\"AOS-R-1.3.0\" -DSYSINFO_APP_VERSION=\"APP-1.0.0\" -DSTDIO_UART=0 -DCONFIG_NO_TCPIP -DRHINO_CONFIG_TICK_TASK=0 -DCONFIG_AOS_KV_MULTIPTN_MODE -DCONFIG_AOS_KV_PTN=6 -DCONFIG_AOS_KV_SECOND_PTN=7 -DCONFIG_AOS_KV_PTN_SIZE=4096 -DCONFIG_AOS_KV_BUFFER_SIZE=8192 -D__BSD_VISIBLE -DRHINO_CONFIG_TICK_TASK=0 -D__MSP432P401R__ -DTARGET_IS_MSP432P4XX -DMX_DEBUG -I"/Applications/ti/ccsv6/tools/compiler/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_button" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_color_led" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_sht20" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_VGM128064" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/hal" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/AliCloud_SDS" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/emhost" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/jsmn" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/inc" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/inc/CMSIS" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/driverlib/MSP432P4xx" -I"/Users/snowyang/workspace/AliOS-Things/include" -I"/Users/snowyang/workspace/AliOS-Things/kernel/rhino/core/include" -I"/Users/snowyang/workspace/AliOS-Things/platform/arch/arm/armv7m/gcc/m4" -I"/Users/snowyang/workspace/AliOS-Things/include/hal" -I"/Users/snowyang/workspace/AliOS-Things/kernel/vcall/aos" -I"/Users/snowyang/workspace/AliOS-Things/board/msp432_launchpad" -ffunction-sections -fdata-sections -fsingle-precision-constant -g -gdwarf-3 -gstrict-dwarf -Wall -std=c99 -fshort-wchar -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o"$@" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

core/k_ringbuf.o: /Users/snowyang/workspace/AliOS-Things/kernel/rhino/core/k_ringbuf.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: GNU Compiler'
	"/Applications/ti/ccsv6/tools/compiler/gcc-arm-none-eabi-4_9-2015q3/bin/arm-none-eabi-gcc" -c -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSYSINFO_OS_VERSION=\"APP-1.0.0\" -DSYSINFO_PRODUCT_MODEL=\"ALI_AOS_STM32L433RCTxP\" -DSYSINFO_DEVICE_NAME=\"STM32L433RCTxP\" -DSYSINFO_KERNEL_VERSION=\"AOS-R-1.3.0\" -DSYSINFO_APP_VERSION=\"APP-1.0.0\" -DSTDIO_UART=0 -DCONFIG_NO_TCPIP -DRHINO_CONFIG_TICK_TASK=0 -DCONFIG_AOS_KV_MULTIPTN_MODE -DCONFIG_AOS_KV_PTN=6 -DCONFIG_AOS_KV_SECOND_PTN=7 -DCONFIG_AOS_KV_PTN_SIZE=4096 -DCONFIG_AOS_KV_BUFFER_SIZE=8192 -D__BSD_VISIBLE -DRHINO_CONFIG_TICK_TASK=0 -D__MSP432P401R__ -DTARGET_IS_MSP432P4XX -DMX_DEBUG -I"/Applications/ti/ccsv6/tools/compiler/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_button" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_color_led" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_sht20" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_VGM128064" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/hal" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/AliCloud_SDS" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/emhost" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/jsmn" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/inc" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/inc/CMSIS" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/driverlib/MSP432P4xx" -I"/Users/snowyang/workspace/AliOS-Things/include" -I"/Users/snowyang/workspace/AliOS-Things/kernel/rhino/core/include" -I"/Users/snowyang/workspace/AliOS-Things/platform/arch/arm/armv7m/gcc/m4" -I"/Users/snowyang/workspace/AliOS-Things/include/hal" -I"/Users/snowyang/workspace/AliOS-Things/kernel/vcall/aos" -I"/Users/snowyang/workspace/AliOS-Things/board/msp432_launchpad" -ffunction-sections -fdata-sections -fsingle-precision-constant -g -gdwarf-3 -gstrict-dwarf -Wall -std=c99 -fshort-wchar -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o"$@" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

core/k_sched.o: /Users/snowyang/workspace/AliOS-Things/kernel/rhino/core/k_sched.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: GNU Compiler'
	"/Applications/ti/ccsv6/tools/compiler/gcc-arm-none-eabi-4_9-2015q3/bin/arm-none-eabi-gcc" -c -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSYSINFO_OS_VERSION=\"APP-1.0.0\" -DSYSINFO_PRODUCT_MODEL=\"ALI_AOS_STM32L433RCTxP\" -DSYSINFO_DEVICE_NAME=\"STM32L433RCTxP\" -DSYSINFO_KERNEL_VERSION=\"AOS-R-1.3.0\" -DSYSINFO_APP_VERSION=\"APP-1.0.0\" -DSTDIO_UART=0 -DCONFIG_NO_TCPIP -DRHINO_CONFIG_TICK_TASK=0 -DCONFIG_AOS_KV_MULTIPTN_MODE -DCONFIG_AOS_KV_PTN=6 -DCONFIG_AOS_KV_SECOND_PTN=7 -DCONFIG_AOS_KV_PTN_SIZE=4096 -DCONFIG_AOS_KV_BUFFER_SIZE=8192 -D__BSD_VISIBLE -DRHINO_CONFIG_TICK_TASK=0 -D__MSP432P401R__ -DTARGET_IS_MSP432P4XX -DMX_DEBUG -I"/Applications/ti/ccsv6/tools/compiler/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_button" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_color_led" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_sht20" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_VGM128064" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/hal" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/AliCloud_SDS" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/emhost" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/jsmn" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/inc" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/inc/CMSIS" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/driverlib/MSP432P4xx" -I"/Users/snowyang/workspace/AliOS-Things/include" -I"/Users/snowyang/workspace/AliOS-Things/kernel/rhino/core/include" -I"/Users/snowyang/workspace/AliOS-Things/platform/arch/arm/armv7m/gcc/m4" -I"/Users/snowyang/workspace/AliOS-Things/include/hal" -I"/Users/snowyang/workspace/AliOS-Things/kernel/vcall/aos" -I"/Users/snowyang/workspace/AliOS-Things/board/msp432_launchpad" -ffunction-sections -fdata-sections -fsingle-precision-constant -g -gdwarf-3 -gstrict-dwarf -Wall -std=c99 -fshort-wchar -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o"$@" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

core/k_sem.o: /Users/snowyang/workspace/AliOS-Things/kernel/rhino/core/k_sem.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: GNU Compiler'
	"/Applications/ti/ccsv6/tools/compiler/gcc-arm-none-eabi-4_9-2015q3/bin/arm-none-eabi-gcc" -c -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSYSINFO_OS_VERSION=\"APP-1.0.0\" -DSYSINFO_PRODUCT_MODEL=\"ALI_AOS_STM32L433RCTxP\" -DSYSINFO_DEVICE_NAME=\"STM32L433RCTxP\" -DSYSINFO_KERNEL_VERSION=\"AOS-R-1.3.0\" -DSYSINFO_APP_VERSION=\"APP-1.0.0\" -DSTDIO_UART=0 -DCONFIG_NO_TCPIP -DRHINO_CONFIG_TICK_TASK=0 -DCONFIG_AOS_KV_MULTIPTN_MODE -DCONFIG_AOS_KV_PTN=6 -DCONFIG_AOS_KV_SECOND_PTN=7 -DCONFIG_AOS_KV_PTN_SIZE=4096 -DCONFIG_AOS_KV_BUFFER_SIZE=8192 -D__BSD_VISIBLE -DRHINO_CONFIG_TICK_TASK=0 -D__MSP432P401R__ -DTARGET_IS_MSP432P4XX -DMX_DEBUG -I"/Applications/ti/ccsv6/tools/compiler/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_button" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_color_led" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_sht20" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_VGM128064" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/hal" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/AliCloud_SDS" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/emhost" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/jsmn" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/inc" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/inc/CMSIS" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/driverlib/MSP432P4xx" -I"/Users/snowyang/workspace/AliOS-Things/include" -I"/Users/snowyang/workspace/AliOS-Things/kernel/rhino/core/include" -I"/Users/snowyang/workspace/AliOS-Things/platform/arch/arm/armv7m/gcc/m4" -I"/Users/snowyang/workspace/AliOS-Things/include/hal" -I"/Users/snowyang/workspace/AliOS-Things/kernel/vcall/aos" -I"/Users/snowyang/workspace/AliOS-Things/board/msp432_launchpad" -ffunction-sections -fdata-sections -fsingle-precision-constant -g -gdwarf-3 -gstrict-dwarf -Wall -std=c99 -fshort-wchar -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o"$@" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

core/k_stats.o: /Users/snowyang/workspace/AliOS-Things/kernel/rhino/core/k_stats.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: GNU Compiler'
	"/Applications/ti/ccsv6/tools/compiler/gcc-arm-none-eabi-4_9-2015q3/bin/arm-none-eabi-gcc" -c -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSYSINFO_OS_VERSION=\"APP-1.0.0\" -DSYSINFO_PRODUCT_MODEL=\"ALI_AOS_STM32L433RCTxP\" -DSYSINFO_DEVICE_NAME=\"STM32L433RCTxP\" -DSYSINFO_KERNEL_VERSION=\"AOS-R-1.3.0\" -DSYSINFO_APP_VERSION=\"APP-1.0.0\" -DSTDIO_UART=0 -DCONFIG_NO_TCPIP -DRHINO_CONFIG_TICK_TASK=0 -DCONFIG_AOS_KV_MULTIPTN_MODE -DCONFIG_AOS_KV_PTN=6 -DCONFIG_AOS_KV_SECOND_PTN=7 -DCONFIG_AOS_KV_PTN_SIZE=4096 -DCONFIG_AOS_KV_BUFFER_SIZE=8192 -D__BSD_VISIBLE -DRHINO_CONFIG_TICK_TASK=0 -D__MSP432P401R__ -DTARGET_IS_MSP432P4XX -DMX_DEBUG -I"/Applications/ti/ccsv6/tools/compiler/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_button" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_color_led" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_sht20" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_VGM128064" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/hal" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/AliCloud_SDS" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/emhost" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/jsmn" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/inc" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/inc/CMSIS" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/driverlib/MSP432P4xx" -I"/Users/snowyang/workspace/AliOS-Things/include" -I"/Users/snowyang/workspace/AliOS-Things/kernel/rhino/core/include" -I"/Users/snowyang/workspace/AliOS-Things/platform/arch/arm/armv7m/gcc/m4" -I"/Users/snowyang/workspace/AliOS-Things/include/hal" -I"/Users/snowyang/workspace/AliOS-Things/kernel/vcall/aos" -I"/Users/snowyang/workspace/AliOS-Things/board/msp432_launchpad" -ffunction-sections -fdata-sections -fsingle-precision-constant -g -gdwarf-3 -gstrict-dwarf -Wall -std=c99 -fshort-wchar -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o"$@" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

core/k_sys.o: /Users/snowyang/workspace/AliOS-Things/kernel/rhino/core/k_sys.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: GNU Compiler'
	"/Applications/ti/ccsv6/tools/compiler/gcc-arm-none-eabi-4_9-2015q3/bin/arm-none-eabi-gcc" -c -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSYSINFO_OS_VERSION=\"APP-1.0.0\" -DSYSINFO_PRODUCT_MODEL=\"ALI_AOS_STM32L433RCTxP\" -DSYSINFO_DEVICE_NAME=\"STM32L433RCTxP\" -DSYSINFO_KERNEL_VERSION=\"AOS-R-1.3.0\" -DSYSINFO_APP_VERSION=\"APP-1.0.0\" -DSTDIO_UART=0 -DCONFIG_NO_TCPIP -DRHINO_CONFIG_TICK_TASK=0 -DCONFIG_AOS_KV_MULTIPTN_MODE -DCONFIG_AOS_KV_PTN=6 -DCONFIG_AOS_KV_SECOND_PTN=7 -DCONFIG_AOS_KV_PTN_SIZE=4096 -DCONFIG_AOS_KV_BUFFER_SIZE=8192 -D__BSD_VISIBLE -DRHINO_CONFIG_TICK_TASK=0 -D__MSP432P401R__ -DTARGET_IS_MSP432P4XX -DMX_DEBUG -I"/Applications/ti/ccsv6/tools/compiler/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_button" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_color_led" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_sht20" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_VGM128064" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/hal" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/AliCloud_SDS" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/emhost" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/jsmn" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/inc" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/inc/CMSIS" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/driverlib/MSP432P4xx" -I"/Users/snowyang/workspace/AliOS-Things/include" -I"/Users/snowyang/workspace/AliOS-Things/kernel/rhino/core/include" -I"/Users/snowyang/workspace/AliOS-Things/platform/arch/arm/armv7m/gcc/m4" -I"/Users/snowyang/workspace/AliOS-Things/include/hal" -I"/Users/snowyang/workspace/AliOS-Things/kernel/vcall/aos" -I"/Users/snowyang/workspace/AliOS-Things/board/msp432_launchpad" -ffunction-sections -fdata-sections -fsingle-precision-constant -g -gdwarf-3 -gstrict-dwarf -Wall -std=c99 -fshort-wchar -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o"$@" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

core/k_task.o: /Users/snowyang/workspace/AliOS-Things/kernel/rhino/core/k_task.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: GNU Compiler'
	"/Applications/ti/ccsv6/tools/compiler/gcc-arm-none-eabi-4_9-2015q3/bin/arm-none-eabi-gcc" -c -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSYSINFO_OS_VERSION=\"APP-1.0.0\" -DSYSINFO_PRODUCT_MODEL=\"ALI_AOS_STM32L433RCTxP\" -DSYSINFO_DEVICE_NAME=\"STM32L433RCTxP\" -DSYSINFO_KERNEL_VERSION=\"AOS-R-1.3.0\" -DSYSINFO_APP_VERSION=\"APP-1.0.0\" -DSTDIO_UART=0 -DCONFIG_NO_TCPIP -DRHINO_CONFIG_TICK_TASK=0 -DCONFIG_AOS_KV_MULTIPTN_MODE -DCONFIG_AOS_KV_PTN=6 -DCONFIG_AOS_KV_SECOND_PTN=7 -DCONFIG_AOS_KV_PTN_SIZE=4096 -DCONFIG_AOS_KV_BUFFER_SIZE=8192 -D__BSD_VISIBLE -DRHINO_CONFIG_TICK_TASK=0 -D__MSP432P401R__ -DTARGET_IS_MSP432P4XX -DMX_DEBUG -I"/Applications/ti/ccsv6/tools/compiler/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_button" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_color_led" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_sht20" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_VGM128064" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/hal" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/AliCloud_SDS" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/emhost" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/jsmn" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/inc" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/inc/CMSIS" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/driverlib/MSP432P4xx" -I"/Users/snowyang/workspace/AliOS-Things/include" -I"/Users/snowyang/workspace/AliOS-Things/kernel/rhino/core/include" -I"/Users/snowyang/workspace/AliOS-Things/platform/arch/arm/armv7m/gcc/m4" -I"/Users/snowyang/workspace/AliOS-Things/include/hal" -I"/Users/snowyang/workspace/AliOS-Things/kernel/vcall/aos" -I"/Users/snowyang/workspace/AliOS-Things/board/msp432_launchpad" -ffunction-sections -fdata-sections -fsingle-precision-constant -g -gdwarf-3 -gstrict-dwarf -Wall -std=c99 -fshort-wchar -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o"$@" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

core/k_task_sem.o: /Users/snowyang/workspace/AliOS-Things/kernel/rhino/core/k_task_sem.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: GNU Compiler'
	"/Applications/ti/ccsv6/tools/compiler/gcc-arm-none-eabi-4_9-2015q3/bin/arm-none-eabi-gcc" -c -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSYSINFO_OS_VERSION=\"APP-1.0.0\" -DSYSINFO_PRODUCT_MODEL=\"ALI_AOS_STM32L433RCTxP\" -DSYSINFO_DEVICE_NAME=\"STM32L433RCTxP\" -DSYSINFO_KERNEL_VERSION=\"AOS-R-1.3.0\" -DSYSINFO_APP_VERSION=\"APP-1.0.0\" -DSTDIO_UART=0 -DCONFIG_NO_TCPIP -DRHINO_CONFIG_TICK_TASK=0 -DCONFIG_AOS_KV_MULTIPTN_MODE -DCONFIG_AOS_KV_PTN=6 -DCONFIG_AOS_KV_SECOND_PTN=7 -DCONFIG_AOS_KV_PTN_SIZE=4096 -DCONFIG_AOS_KV_BUFFER_SIZE=8192 -D__BSD_VISIBLE -DRHINO_CONFIG_TICK_TASK=0 -D__MSP432P401R__ -DTARGET_IS_MSP432P4XX -DMX_DEBUG -I"/Applications/ti/ccsv6/tools/compiler/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_button" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_color_led" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_sht20" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_VGM128064" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/hal" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/AliCloud_SDS" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/emhost" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/jsmn" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/inc" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/inc/CMSIS" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/driverlib/MSP432P4xx" -I"/Users/snowyang/workspace/AliOS-Things/include" -I"/Users/snowyang/workspace/AliOS-Things/kernel/rhino/core/include" -I"/Users/snowyang/workspace/AliOS-Things/platform/arch/arm/armv7m/gcc/m4" -I"/Users/snowyang/workspace/AliOS-Things/include/hal" -I"/Users/snowyang/workspace/AliOS-Things/kernel/vcall/aos" -I"/Users/snowyang/workspace/AliOS-Things/board/msp432_launchpad" -ffunction-sections -fdata-sections -fsingle-precision-constant -g -gdwarf-3 -gstrict-dwarf -Wall -std=c99 -fshort-wchar -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o"$@" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

core/k_tick.o: /Users/snowyang/workspace/AliOS-Things/kernel/rhino/core/k_tick.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: GNU Compiler'
	"/Applications/ti/ccsv6/tools/compiler/gcc-arm-none-eabi-4_9-2015q3/bin/arm-none-eabi-gcc" -c -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSYSINFO_OS_VERSION=\"APP-1.0.0\" -DSYSINFO_PRODUCT_MODEL=\"ALI_AOS_STM32L433RCTxP\" -DSYSINFO_DEVICE_NAME=\"STM32L433RCTxP\" -DSYSINFO_KERNEL_VERSION=\"AOS-R-1.3.0\" -DSYSINFO_APP_VERSION=\"APP-1.0.0\" -DSTDIO_UART=0 -DCONFIG_NO_TCPIP -DRHINO_CONFIG_TICK_TASK=0 -DCONFIG_AOS_KV_MULTIPTN_MODE -DCONFIG_AOS_KV_PTN=6 -DCONFIG_AOS_KV_SECOND_PTN=7 -DCONFIG_AOS_KV_PTN_SIZE=4096 -DCONFIG_AOS_KV_BUFFER_SIZE=8192 -D__BSD_VISIBLE -DRHINO_CONFIG_TICK_TASK=0 -D__MSP432P401R__ -DTARGET_IS_MSP432P4XX -DMX_DEBUG -I"/Applications/ti/ccsv6/tools/compiler/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_button" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_color_led" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_sht20" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_VGM128064" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/hal" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/AliCloud_SDS" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/emhost" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/jsmn" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/inc" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/inc/CMSIS" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/driverlib/MSP432P4xx" -I"/Users/snowyang/workspace/AliOS-Things/include" -I"/Users/snowyang/workspace/AliOS-Things/kernel/rhino/core/include" -I"/Users/snowyang/workspace/AliOS-Things/platform/arch/arm/armv7m/gcc/m4" -I"/Users/snowyang/workspace/AliOS-Things/include/hal" -I"/Users/snowyang/workspace/AliOS-Things/kernel/vcall/aos" -I"/Users/snowyang/workspace/AliOS-Things/board/msp432_launchpad" -ffunction-sections -fdata-sections -fsingle-precision-constant -g -gdwarf-3 -gstrict-dwarf -Wall -std=c99 -fshort-wchar -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o"$@" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

core/k_time.o: /Users/snowyang/workspace/AliOS-Things/kernel/rhino/core/k_time.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: GNU Compiler'
	"/Applications/ti/ccsv6/tools/compiler/gcc-arm-none-eabi-4_9-2015q3/bin/arm-none-eabi-gcc" -c -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSYSINFO_OS_VERSION=\"APP-1.0.0\" -DSYSINFO_PRODUCT_MODEL=\"ALI_AOS_STM32L433RCTxP\" -DSYSINFO_DEVICE_NAME=\"STM32L433RCTxP\" -DSYSINFO_KERNEL_VERSION=\"AOS-R-1.3.0\" -DSYSINFO_APP_VERSION=\"APP-1.0.0\" -DSTDIO_UART=0 -DCONFIG_NO_TCPIP -DRHINO_CONFIG_TICK_TASK=0 -DCONFIG_AOS_KV_MULTIPTN_MODE -DCONFIG_AOS_KV_PTN=6 -DCONFIG_AOS_KV_SECOND_PTN=7 -DCONFIG_AOS_KV_PTN_SIZE=4096 -DCONFIG_AOS_KV_BUFFER_SIZE=8192 -D__BSD_VISIBLE -DRHINO_CONFIG_TICK_TASK=0 -D__MSP432P401R__ -DTARGET_IS_MSP432P4XX -DMX_DEBUG -I"/Applications/ti/ccsv6/tools/compiler/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_button" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_color_led" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_sht20" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_VGM128064" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/hal" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/AliCloud_SDS" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/emhost" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/jsmn" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/inc" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/inc/CMSIS" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/driverlib/MSP432P4xx" -I"/Users/snowyang/workspace/AliOS-Things/include" -I"/Users/snowyang/workspace/AliOS-Things/kernel/rhino/core/include" -I"/Users/snowyang/workspace/AliOS-Things/platform/arch/arm/armv7m/gcc/m4" -I"/Users/snowyang/workspace/AliOS-Things/include/hal" -I"/Users/snowyang/workspace/AliOS-Things/kernel/vcall/aos" -I"/Users/snowyang/workspace/AliOS-Things/board/msp432_launchpad" -ffunction-sections -fdata-sections -fsingle-precision-constant -g -gdwarf-3 -gstrict-dwarf -Wall -std=c99 -fshort-wchar -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o"$@" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

core/k_timer.o: /Users/snowyang/workspace/AliOS-Things/kernel/rhino/core/k_timer.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: GNU Compiler'
	"/Applications/ti/ccsv6/tools/compiler/gcc-arm-none-eabi-4_9-2015q3/bin/arm-none-eabi-gcc" -c -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSYSINFO_OS_VERSION=\"APP-1.0.0\" -DSYSINFO_PRODUCT_MODEL=\"ALI_AOS_STM32L433RCTxP\" -DSYSINFO_DEVICE_NAME=\"STM32L433RCTxP\" -DSYSINFO_KERNEL_VERSION=\"AOS-R-1.3.0\" -DSYSINFO_APP_VERSION=\"APP-1.0.0\" -DSTDIO_UART=0 -DCONFIG_NO_TCPIP -DRHINO_CONFIG_TICK_TASK=0 -DCONFIG_AOS_KV_MULTIPTN_MODE -DCONFIG_AOS_KV_PTN=6 -DCONFIG_AOS_KV_SECOND_PTN=7 -DCONFIG_AOS_KV_PTN_SIZE=4096 -DCONFIG_AOS_KV_BUFFER_SIZE=8192 -D__BSD_VISIBLE -DRHINO_CONFIG_TICK_TASK=0 -D__MSP432P401R__ -DTARGET_IS_MSP432P4XX -DMX_DEBUG -I"/Applications/ti/ccsv6/tools/compiler/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_button" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_color_led" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_sht20" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_VGM128064" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/hal" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/AliCloud_SDS" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/emhost" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/jsmn" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/inc" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/inc/CMSIS" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/driverlib/MSP432P4xx" -I"/Users/snowyang/workspace/AliOS-Things/include" -I"/Users/snowyang/workspace/AliOS-Things/kernel/rhino/core/include" -I"/Users/snowyang/workspace/AliOS-Things/platform/arch/arm/armv7m/gcc/m4" -I"/Users/snowyang/workspace/AliOS-Things/include/hal" -I"/Users/snowyang/workspace/AliOS-Things/kernel/vcall/aos" -I"/Users/snowyang/workspace/AliOS-Things/board/msp432_launchpad" -ffunction-sections -fdata-sections -fsingle-precision-constant -g -gdwarf-3 -gstrict-dwarf -Wall -std=c99 -fshort-wchar -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o"$@" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

core/k_workqueue.o: /Users/snowyang/workspace/AliOS-Things/kernel/rhino/core/k_workqueue.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: GNU Compiler'
	"/Applications/ti/ccsv6/tools/compiler/gcc-arm-none-eabi-4_9-2015q3/bin/arm-none-eabi-gcc" -c -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSYSINFO_OS_VERSION=\"APP-1.0.0\" -DSYSINFO_PRODUCT_MODEL=\"ALI_AOS_STM32L433RCTxP\" -DSYSINFO_DEVICE_NAME=\"STM32L433RCTxP\" -DSYSINFO_KERNEL_VERSION=\"AOS-R-1.3.0\" -DSYSINFO_APP_VERSION=\"APP-1.0.0\" -DSTDIO_UART=0 -DCONFIG_NO_TCPIP -DRHINO_CONFIG_TICK_TASK=0 -DCONFIG_AOS_KV_MULTIPTN_MODE -DCONFIG_AOS_KV_PTN=6 -DCONFIG_AOS_KV_SECOND_PTN=7 -DCONFIG_AOS_KV_PTN_SIZE=4096 -DCONFIG_AOS_KV_BUFFER_SIZE=8192 -D__BSD_VISIBLE -DRHINO_CONFIG_TICK_TASK=0 -D__MSP432P401R__ -DTARGET_IS_MSP432P4XX -DMX_DEBUG -I"/Applications/ti/ccsv6/tools/compiler/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_button" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_color_led" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_sht20" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/drv_VGM128064" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/hal" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/AliCloud_SDS" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/emhost" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/examples/MSP432P4xx/mxchip/iot_sdk/Board/helper/jsmn" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/inc" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/inc/CMSIS" -I"/Users/snowyang/workspace/AliOS-Things/platform/mcu/msp432/IOT-MSP432/driverlib/MSP432P4xx" -I"/Users/snowyang/workspace/AliOS-Things/include" -I"/Users/snowyang/workspace/AliOS-Things/kernel/rhino/core/include" -I"/Users/snowyang/workspace/AliOS-Things/platform/arch/arm/armv7m/gcc/m4" -I"/Users/snowyang/workspace/AliOS-Things/include/hal" -I"/Users/snowyang/workspace/AliOS-Things/kernel/vcall/aos" -I"/Users/snowyang/workspace/AliOS-Things/board/msp432_launchpad" -ffunction-sections -fdata-sections -fsingle-precision-constant -g -gdwarf-3 -gstrict-dwarf -Wall -std=c99 -fshort-wchar -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o"$@" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


